name: Build Aimlock SO
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26b
        add-to-path: true
    - name: Build
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        TARGET=aarch64-linux-android
        API=21
        $TOOLCHAIN/bin/${TARGET}${API}-clang++ \
          -shared -fPIC -O2 -s \
          -o aimlock.so aimlock.cpp \
          -llog -ldl -pthread
    - uses: actions/upload-artifact@v4
      with:
        name: aimlock-so
        path: aimlock.so